- name: Create interface for management VLAN
  community.proxmox.proxmox_node_network:
    api_host: '{{ api_host }}'
    api_user: '{{ api_user }}'
    api_token_id: '{{ api_token_id }}'
    api_token_secret: '{{ api_token_secret }}'
    node: proxmox1
    state: present
    iface: nic0.2
    iface_type: vlan

- name: Create interface for server VLAN
  community.proxmox.proxmox_node_network:
    api_host: '{{ api_host }}'
    api_user: '{{ api_user }}'
    api_token_id: '{{ api_token_id }}'
    api_token_secret: '{{ api_token_secret }}'
    node: proxmox1
    state: present
    iface: nic0.3
    iface_type: vlan

- name: Create bridge for management VLAN
  community.proxmox.proxmox_node_network:
    api_host: '{{ api_host }}'
    api_user: '{{ api_user }}'
    api_token_id: '{{ api_token_id }}'
    api_token_secret: '{{ api_token_secret }}'
    node: proxmox1
    state: present
    iface: vmbr2
    iface_type: bridge
    cidr: '{{ ansible_host }}/24'
    gateway: '{{ ansible_host | regex_replace("^(.+)\.[^.]+$", "\1") }}.1'
    autostart: true

- name: Create bridge for server VLAN
  community.proxmox.proxmox_node_network:
    api_host: '{{ api_host }}'
    api_user: '{{ api_user }}'
    api_token_id: '{{ api_token_id }}'
    api_token_secret: '{{ api_token_secret }}'
    node: proxmox1
    state: present
    iface: vmbr3
    iface_type: bridge
    autostart: true
